title: Stanislav KukuÄka - SEO, ASO, PPC / Personal website
email: stan.kukucka@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm open to working with motivated folks or teams on courageous & fluffy digital products that are like munchies to certain market.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stanislav-kukucka.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username: stanislav-kukucka

google_analytics: G-T51R040NRN
linkedin_username: stankukucka
author: Stanislav Kukucka

# Build settings
markdown: kramdown
paginate: 10
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
